# Dockerfile.worker
FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV SERVICE_TYPE=worker

CMD ["sh", "-c", "if [ \"$SERVICE_TYPE\" = 'celery' ]; then celery -A celery_app worker --loglevel=info; else python run_worker.py; fi"]
