# render.yaml
services:
  # Your existing Flask web service
  - type: web
    name: python-whatsapp-bot
    runtime: python
    region: oregon                    # or your desired region
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app   # or however you start Flask

